config/routes.rb
Rails.application.routes.draw do

resources :items
resources :meal_plan
root to: 'welcome#show'
  #For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item<ApplicationRecord
  belongs_to :user
  validates :name, presence: true, uniqueness: {scope: :user_id}
  validates :description, presence: true
  validates :user, presence: true

end

app/models/meal.rb
class Meal < ApplicationRecord
belongs_to :meal_plan, inverse_of: :meals
belongs_to :item
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  belongs_to :user
  has_many :meals, -> {order(:date)}, inverse_of: :meal_plan, dependent: :destroy
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :user, presence: true
 accepts_nested_attributes_for :meals
  def build_meals
    user_items_ids=user.items.pluck(:id)

    (start_date..end_date).each do |date|
      unused_item_ids=user_items_ids-meals.map(&:item_id)
      if unused_item_ids.empty?
        available_item_ids=user_items_ids
      else
        available_item_ids=unused_item_ids
      end
      meals.build(date: date, item_id: available_item_ids.sample)
    end
  end
  def to_s
    "#{start_date}   -   #{end_date}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :items
  has_many :meal_plans

  def item_options
  items.map do |item|
    [item.name, item.id]
  end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_login
  def index
    @current_user = current_user.items.ids
    @items=Item.all
  end
  def show
    @item=Item.find(params[:id])

  end
  def new
   @item=current_user.items.build
  end
  def edit
    @item=current_user.items.find(params[:id])
  end
  def create
  @item=current_user.items.build(item_params)
    if  @item.save
      redirect_to item_path(@item), notice: "Item is created"
    else
      @errors=@item.errors.full_messages
      render :new
    end
  end
  def update
    @item=current_user.items.find(params[:id])

    if  @item.update_attributes(item_params)
      redirect_to item_path(@item), notice: "Item is created"
    else
      @errors=@item.errors.full_messages
      render :edit
    end
  end
  def destroy
    @item=current_user.items.find(params[:id])
   if  @item.destroy
    redirect_to items_path, notice: "you have deleted #{@item.name}"
   else
     @errors=@item.errors.full_messages
     render :new
   end
    end
  private
  def item_params
    params.require(:item).permit(:name,:description)
  end
end

app/controllers/meal_plan_controller.rb
class MealPlanController < ApplicationController
  before_action :require_login
  def index
 @current_meal_plan=current_user.meal_plans.where("start_date <= ?  AND end_date >= ?", Date.today, Date.today).first
  @meal_plans=current_user.meal_plans.all
  end


  def show
    @meal_plan=current_user.meal_plans.find(params[:id])

  end


  def new
@meal_plan=current_user.meal_plans.build(
        start_date: params[:start_date] || Date.today,
        end_date: params[:end_date] || 6.days.from_now.to_date)
@meal_plan.build_meals
  end


  def edit
 @meal_plan=current_user.meal_plans.find(params[:id])
  end


  def create
 @meal_plan=current_user.meal_plans.build(meal_plan_params)
    if @meal_plan.save
      redirect_to meal_plan_path(@meal_plan), notice: "you have created a meal plan"
    else
       puts @meal_plan.errors.inspect
      @errors=@meal_plan.errors.full_messages
      render :new
    end
  end


  def update
    @meal_plan=current_user.meal_plans.find(params[:id])
    if @meal_plan.update_attributes(meal_plan_params)
      redirect_to meal_plan_path(@meal_plan), notice: "you have edited a meal plan"
    else
      puts @meal_plan.errors.inspect
      @errors=@meal_plan.errors.full_messages
  end

end

  def destroy
 @meal_plan=current_user.meal_plans.find(params[:id])
    @meal_plan.destroy
    redirect_to meal_plan_index_path, notice: "meal plan is deleted"
  end






  private
  def meal_plan_params
    params.require(:meal_plan).permit(
                                  :start_date,
                                  :end_date,
                                   meals_attributes: [:id, :date, :item_id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class(flash_type)
    case flash_type.to_sym
    when :notice
      "alert-success"
    when :alert
      "alert-warning"
    when :error
      "alert-danger"
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/meal_plan_helper.rb
module MealPlanHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%=form_for @item do |form| %>
  <div class="form-group">
   <strong><%=form.label :name  %></strong> <br>
    <%=form.text_field :name , class: "form-control" %>
  </div>

  <div class="form-group">
   <strong><%=form.label :description  %></strong> <br>
    <%= form.text_area :description , class: "form-control"  %>
  </div>

  <div class="actions">
    <%=form.submit class: "btn btn-primary" %>
  </div>
<%end %>

app/views/items/edit.html.erb
<h1>Edit items</h1>
<% if @errors.present? %>
  <div class="errors">
    <ul>
      <% @errors.each do |error| %>
        <li><%= error %></li>
      <%end %>
    </ul>
  </div>
<%else %>
<%= render partial: "form" %>
<%end %>

app/views/items/index.html.erb
<div class="title-container">
  <h1>Items</h1>
  <%= link_to "Add new Item",new_item_path, class: "btn btn-default" %>
</div>

<div class="items">
  <% @items.each do |item| %>
  <div class="item">
    <div class="thumbnail">
      <div class="caption">
    <h3><%= link_to item.name, item_path(item) %></h3>
    <p> <%=item.description %></p>
    <p>
      <%var1=current_user.id %>
      <%var2=item.user_id %>
      <%if var1==var2 %>
       <%= link_to "Edit", edit_item_path(item) , class: "btn btn-default" %>
     <%= link_to "Delete", item_path(item), data: {confirm: "are you sure to delete #{item.name}?"},
                        method: :delete , class: "btn btn-default" %>
      <% end %>
    </p>
      </div>
    </div>
  </div>
    </div>
  </div>

  <% end %>
</div>

app/views/items/new.html.erb
<h1>New item</h1>
<% if @errors.present? %>
  <div class="errors">
    <ul>
      <% @errors.each do |error| %>
        <li><%= error %></li>
      <%end %>
    </ul>
  </div>
<%end %>
<%=render partial: "form" %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<h2> Description:</h2>
<p><%= @item.description %></p>
  <div>
    <ul class="item-actions">
      <li><%=link_to "Back",items_path %></li>
      <%var1=current_user.id %>
      <%var2=@item.user_id %>
      <%if var1==var2 %>
          <li><%= link_to "Edit", edit_item_path(@item) %></li>
          <li><%= link_to "Delete", item_path(@item), data: {confirm: "are you sure to delete #{@item.name}?"},
                          method: :delete %></li>
      <% end %>
  </ul>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Demorres</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
          <%= link_to "Meal Planning", root_path,class: "navbar-brand" %>
            <%= image_tag('parrots/beerparrot.gif',:width => 30, :height => 40) %>
        </div>
        <ul class="nav navbar-nav navbar-right">

          <% if signed_in? %>
            <li> <%=link_to "Meal Plan", meal_plan_index_path %></li>
            <li> <%=link_to "Items", items_path %></li>
            <li> <%=link_to "Sign Out", sign_out_path, method: :delete %></li>
            <%#Signed in as: <%= current_user.email %>
            <%#= button_to 'Sign out', , method: :delete %>
          <% else %>
           <li><%= link_to 'Sign in', sign_in_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    </header>

    <section class="container">
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash alert <%= alert_class(key) %>"><%= value %></div>
        <% end %>
      </div>
      <%= yield %>
    </section>

    </body>
  </html>

app/views/meal_plan/_form.html.erb
<%= render partial: "shared/error" %>
<%=form_with scope: @meal_plan, url: meal_plan_index_path, local: true do |form| %>
  <%= form.hidden_field :start_date %>
  <%= form.hidden_field :end_date %>

  <div class="meals">
    <%= form.fields_for :meals do |meal_fields| %>
      <%=meal_fields.hidden_field :id %>
      <%=meal_fields.hidden_field :date %>
      <p> <%= meal_fields.object.date.to_s %></p>
      <div class="form-control">
        <%= meal_fields.label :item_id %>
        <%= meal_fields.select :item_id, current_user.item_options %>
        <br>   <br>
      </div>
      <br>
      <%end %>
      </div>

  <div class="actions">
    <%=form.submit %>

  </div>
<%end %>

app/views/meal_plan/edit.html.erb
<h1>Edit your Meal Plan <%=@meal_plan %></h1>

<%=form_with model: @meal_plan, local: true do |form| %>
  <%= form.hidden_field :start_date %>
  <%= form.hidden_field :end_date %>

  <div class="meals">
    <%= form.fields_for :meals do |meal_fields| %>
      <%=meal_fields.hidden_field :id %>
      <%=meal_fields.hidden_field :date %>
      <p> <%= meal_fields.object.date.to_s %></p>

      <div class="form-control">
        <%= meal_fields.label :item_id %>
        <%= meal_fields.select :item_id, current_user.item_options %>
      </div>
    <%end %>
  </div>

  <div class="actions">
    <%=form.submit %>

  </div>
<%end %>

app/views/meal_plan/index.html.erb
<h1> Meal Plans </h1>
<%#= image_tag("/Users/tamal/Documents/GitHub/WellFoodDemo/app/assets/images/parrots/angelparrot.gif",height: '32', width: '32') %>

<%#= render partial: "shared/error" %>
<% if @current_meal_plan.present? %>

<ul class="meals">
  <% meal_plan = @current_meal_plan.meals %>
  <% meal_plan.each do |mealpp| %>
    <li class="meal">
      <%= mealpp.date %> - <%=link_to mealpp.item.name, item_path(mealpp.item) %>
    </li>
  <% end %>
</ul>
<%end %>
<strong> All the created meal plans</strong>
<% if  @meal_plans.present? %>

  <ul class="meals">

    <% @meal_plans.each do |mealpp| %>
      <li class="meal">
       <%= mealpp.start_date%> ---<%=mealpp.end_date %>
        <%= link_to "View", meal_plan_path(mealpp), class: "btn btn-default" %>
        <%=link_to "Edit",  edit_meal_plan_path(mealpp), class: "btn btn-default" %>
        <%=link_to 'Delete', meal_plan_path(mealpp), method: :delete, data:{confirm: "are you sure?"} , class: "btn btn-default" %>
      </li>

    <% end %>
  </ul>
<% else %>
  <strong> khuje paai ni bhai</strong>
<%end %>
<p>
  <%= link_to 'New plan',  new_meal_plan_path, class: "btn btn-default" %>
</p>

app/views/meal_plan/new.html.erb
<div class="title-container"><h1>New Meal Plan</h1>
</div>

<%= form_for @meal_plan, url: new_meal_plan_path, method: "GET" do |form| %>
  <div class="form-control">
    <strong><%=form.label :start_date  %></strong> <br>
    <%=form.date_field :start_date, type: "date"  %>
  </div>
<br> <br>
  <div class="form-control">
    <strong><%=form.label :end_date  %></strong> <br>
    <%=form.date_field :end_date, type: "date"  %>
  </div>
<br> <br>
  <div class="actions">
    <%=form.submit %>
  </div>
<%end %>
<br>
<%=render partial: "form" %>

app/views/meal_plan/show.html.erb
<h1>Meal Plan <%=@meal_plan %></h1>
<%#= render partial: "shared/error" %>
<ul class="meals">
  <% meals = @meal_plan.meals %>
  <% meals.each do |meal| %>
    <li class="meal">
      <%= meal.date %> - <%=link_to meal.item.name, item_path(meal.item) %>
    </li>
  <% end %>

</ul>

app/views/shared/_error.html.erb
<% if @errors.present? %>
  <div class="errors">
    <ul>
      <% @errors.each do |error| %>
        <li><%= error %></li>
      <%end %>
    </ul>
  </div>
<%end %>

app/views/welcome/show.html.erb
<Strong> Welcome in WellFood </Strong>
<br>
<%= link_to 'Lets Go', items_path %>